# Avoids "Unable to connect to WSGI daemon process 'datavis ' on
# '/run/httpd/wsgi.15643.0.1.sock' after multiple attempts.
# Cannot be within a VirtualHost directive.
WSGISocketPrefix /var/run/wsgi

<VirtualHost *:80>
	ServerAdmin webmaster@ucar.edu
	ServerName datavis.eol.ucar.edu
	# ServerAlias www.eol.ucar.edu
	ErrorLog /var/log/httpd/datavis.log

  SetEnv DJANGO_SETTINGS_MODULE datavis.settings.production

	WSGIDaemonProcess datavis processes=2 display-name=%{GROUP} threads=25 python-path=/var/django/eol-django-datavis:/var/django/eol-django-datavis/datavis:/var/django/virtualenv/django/lib/python3.3/site-packages

	WSGIProcessGroup datavis

	<Directory /var/django/eol-django-datavis>
		<IfVersion < 2.3 >
			Order allow,deny
			Allow from all
		</IfVersion>
		<IfVersion >= 2.3>
			Require all granted
		</IfVersion>
	</Directory>
	WSGIScriptAlias / /var/django/eol-django-datavis/datavis/wsgi.py

	Alias /media/ /var/django/eol-django-datavis/media/
	<Directory /var/django/eol-django-datavis/media>
		<IfVersion < 2.3 >
			Order allow,deny
			Allow from all
		</IfVersion>
		<IfVersion >= 2.3>
			Require all granted
		</IfVersion>
	</Directory>

	Alias /static/ /var/django/eol-django-datavis/static/
	<Directory /var/django/eol-django-datavis/static>
		<IfVersion < 2.3 >
			Order allow,deny
			Allow from all
		</IfVersion>
		<IfVersion >= 2.3>
			Require all granted
		</IfVersion>
	</Directory>
	<Location "/static/">
	    Options -Indexes
	</Location>
</VirtualHost>
